---
title: "Midterm project"
author: "Yuanming LENG"
date: "'r sys'"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(readxl)
library(tidyr)
library(base)
Pest <- read.csv("Pesticides.csv")
Pest <- Pest[Pest$Pesticide != "",]

strawb <- read.csv("Strawberries.csv",fileEncoding= "latin1")
```

#整理数据集
```{r}
drop_no_info_cols <- function(df){
  cnames = colnames(strawb)
  T = NULL
  for(i in 1:ncol(df)){
    T <- c(T, nrow(unique(df[i])))
    }
  drop_cols <- cnames[which(T == 1)]
  return(df[, !names(df) %in% all_of(drop_cols)])
}
strawb <- drop_no_info_cols(strawb)

strawb %<>% separate(col=Data.Item,
                into = c("Strawberries", "items", "discription", "units"),
                sep = ",",
                fill = "right")

strawb %<>%  separate(col=Domain,
                      into = c("dname", "type" ), 
                      sep = ",", 
                      fill = "right")

strawb %<>% 
  mutate(Chemicals = Domain.Category) %>% 
  relocate(Chemicals, .after = Domain.Category) 

strawb %<>% separate(col = Chemicals,
                               into = c("title", "details"),
                               sep = ":",
                               fill = "right")

strawb %<>% mutate(details = str_extract(str_trim(details) ,"[^(].*[^)]") )

strawb %<>% mutate(type = str_trim(type))


for (i in 1:nrow(strawb[is.na(strawb$details),])) {
        strawb[is.na(strawb$details),]$details <- rep("NOT SPECIFIED", nrow(strawb[is.na(strawb$details),]))
      }
   
for (i in 1:nrow(strawb[is.na(strawb$type),])) {
        strawb[is.na(strawb$type),]$type <- strawb[is.na(strawb$type),]$dname
}
 
bb <- strawb$discription %>% str_detect("MEASURED")
bb[is.na(bb)] <- FALSE
## index 
ind_C <- (!bb)*(1:dim(strawb)[1])
## 
r1 <- ind_C[ind_C > 0]
## set entries in Chemicals column to " " if they don't start with CHEM
strawb$discription[r1] <- strawb$units[r1]

strawb %<>%  separate(col=details,
                      into = c("details", "No." ), 
                      sep = "=", 
                      fill = "right")
strawb %<>% mutate(Value = str_extract(str_trim(Value) ,"[^(].*[^)]") )
strawb$Value[strawb$Value == "NA"] <- NA
strawb <- strawb[!is.na(strawb$discription) & !is.na(strawb$Value),]

strawb$Value  <-  as.numeric(gsub( ",","",strawb$Value))
strawb %<>% mutate(discription = str_trim(discription))

strawb$Value[strawb$discription == "MEASURED IN CWT" ] <- strawb$Value[strawb$discription == "MEASURED IN CWT" ]*100
strawb$discription[strawb$discription == "MEASURED IN CWT"] <- rep("MEASURED IN LB", length(strawb$discription[strawb$discription == "MEASURED IN CWT" ]))
strawb1 <- data.frame("year" = strawb$Year, "state" = strawb$State, "measurement(s)" = strawb$discription, "chemical" = strawb$details, "chemical.type" = strawb$type, "value" = strawb$Value)
```



```{r}
# strawb_fungi <- strawb1 %>% filter((chemical.type=="FUNGICIDE"))
# strawb_herb <- strawb1 %>% filter((chemical.type=="HERBICIDE"))
# strawb_insect <- strawb1 %>% filter((chemical.type=="INSECTICIDE"))




```

