---
title: "visualization_strawb"
author: "iamqb"
date: "10/31/2021"
output: html_document
---

```{R}
library(magrittr)
library(tidyselect)
library(readxl)
library(tidyr)
library(base)
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyverse)
library(maps)
library(sf)
library(cowplot)
library(usmap)
library(plotly)

source(file = "strawbData.R", echo = TRUE)

```


# plot1
```{r}

# yearly value of strawberries in each state
plot1 <- function(measurement = "MEASURED IN LB"){
  
  if (measurement == "MEASURED IN LB"){
    
  ggplot(data=measure_LB) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in LB")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
  
    
  }
  
  else if (measurement == "MEASURED IN AB"){
    
  ggplot(data=measure_AB) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in AB")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
    
  }
  
  else if (measurement == "MEASURED IN Dollar"){
    
  ggplot(data=measure_dollar) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in Dollar")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
    
  }
  
  else if (measurement == "MEASURED IN LAAP"){
    
  ggplot(data=measure_LAAP) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in LAAP")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
    
  }

  else if (measurement == "MEASURED IN LAyear"){
    
  ggplot(data=measure_LAyear) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in LAyear")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
    
  }
  
  else if (measurement == "MEASURED IN Number"){
    
  ggplot(data=measure_number) +
  geom_bar(mapping = aes(x=factor(chemical.type, levels=c("organic"="ORGANIC STATUS", "fungi"="FUNGICIDE", "herb"="HERBICIDE", "insect"="INSECTICIDE", "other" = "OTHER", "fert"="FERTILIZER")), y=log(value), fill=state), 
           stat="identity", position= 'dodge', alpha=0.8) +
  labs(x="year", y="log of measurement in number")+
  coord_polar()+
  facet_wrap(~factor(year)) +
  theme_bw()+
  theme(text=element_text(size=25))
#ggsave('plot1.png', width=20, height=20, dpi=450)
    
  }  
}

plot1()

```


# plot2
```{R}
#chemical type related value in each state in LB

# yearly value of strawberries in each state
plot2 <- function(measurement = "MEASURED IN LB"){
  
  if (measurement == "MEASURED IN LB"){
    
    for (i in 1:length(unique(measure_LB$chemical.type))) {
      print(ggplot(data = measure_LB[measure_LB$chemical.type == unique(measure_LB$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
      }
    }
  
  else if (measurement == "MEASURED IN AB"){
    
    for (i in 1:length(unique(measure_AB$chemical.type))) {
      print(ggplot(data = measure_AB[measure_AB$chemical.type == unique(measure_AB$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
    }
  }
  
  else if (measurement == "MEASURED IN Dollar"){

    for (i in 1:length(unique(measure_dollar$chemical.type))) {
      print(ggplot(data = measure_dollar[measure_dollar$chemical.type == unique(measure_dollar$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
    }
  }
  
  else if (measurement == "MEASURED IN LAAP"){
    
    for (i in 1:length(unique(measure_LAAP$chemical.type))) {
      print(ggplot(data = measure_LAAP[measure_LAAP$chemical.type == unique(measure_LAAP$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
    }
  }

  else if (measurement == "MEASURED IN LAyear"){
    
    for (i in 1:length(unique(measure_LAyear$chemical.type))) {
      print(ggplot(data = measure_LAyear[measure_LAyear$chemical.type == unique(measure_LAyear$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
    }
  }
  
  else if (measurement == "MEASURED IN Number"){
    
    for (i in 1:length(unique(measure_number$chemical.type))) {
      print(ggplot(data = measure_number[measure_number$chemical.type == unique(measure_number$chemical.type)[i],])+ 
      geom_bar(mapping= aes(x = chemical, y= log(value), fill=chemical.type), 
               stat='identity', alpha= 0.8)+
      labs(title="") +
      theme(text=element_text(size=15))+
      coord_polar()+
      theme_bw())
    }
  }
}

plot2()


```

# map
```{r}

map <-function(years = "2019",state = "CALIFORNIA", 
               chemical = "NOP USDA CERTIFIED", measurement = "MEASURED IN LB"){
  
  usmap::plot_usmap(data = strawb1[strawb1$year==years & 
                                     strawb1$state == state & 
                                     strawb1$chemical == chemical & 
                                     strawb1$`measurement.s.` == measurement,], 
                    
                    values = "value", 
                    color = "pink",  size = 1,
                    labels = T, label_color = "grey") +

    
   # geom_point(data = strawb1[strawb1$year==years & 
    #                                 strawb1$state == state & 
     #                                strawb1$chemical == chemical & 
     #                                strawb1$`measurement.s.` == measurement,])+
    
    ggplot2::scale_fill_continuous(low = "white", high = "red", name = "", label = scales::comma)+ 
    ggplot2::theme(legend.position = "right")
}

map()

```



